version: '3.8'
services:
  nuxt:
    build: ./nuxt
    ports:
      - 9001:3000
    volumes:
      - ./nuxt/src:/nuxt
    working_dir: /nuxt
    command: npm run dev
  express:
    build: ./express
    ports:
      - 8080:10000
    volumes:
      - ./express:/express
    working_dir: /express
    command: npm start